### ISSUE TITLE
第22页 而对于jQuery或其他插件，我们需要使用shim机制下面的代码错误。

### ISSUE THREAD

**Issue by mingliao** [RubyLouvre/jsbook#100]
代码错误？没看到下面的代码有显示shim的配置。是否代码写错了？

**Comment by RubyLouvre** [comment]
http://avalonjs.github.io/#zh/engineering/jquery.html  我看看

**Comment by mingliao** [comment]
恩，如果您的书籍中有使用到requirejs的话，这个代码应该是介绍requirejs里面的shim的用法【jquery插件使用之前要先引入jquery配置】，如果没有的话，应该是mass.js里面有类似shim的配置定义。不过我看您这里写的似乎没有介绍到，是不是代码贴错了。望指正。谢谢。

**Comment by RubyLouvre** [comment]
我在下一版修正吧;下一版将更换成avalon做演示代码了

**Comment by mingliao** [comment]
好，期待大作，O(∩_∩)O
