### ISSUE TITLE
#第11章 移动端的事件系统 <错字及语义不详>

### ISSUE THREAD

**Issue by michael829** [RubyLouvre/jsbook#128]
**位置:** 第1段
**问题:** 文字错误及语义不详:
**原文:**
_移动端不同于PC端，许多事件是不`[呆]`用的，需要合成多个原始事件模拟某一个可用的事件出来。究其原因，最早在移动端发迹的苹果给我们带来各种各样的奇葩BUG或怪异设定，安卓也无脑照抄但又抄也抄不好，带来更多BUG所致。_
**建议:**
移动端事件不同于PC端, 许多PC端的事件在移动端是不可用, 需要综合多个原始事件模拟出某一个可用的事件. 究其原因, 是由于最早在移动端发迹的IOS给我们带来各种各样的奇葩BUG或怪异设定，安卓也无脑照抄但又抄不好，带来更多BUG所致。

**位置:** 第2段
**问题:** 文字错误及语义不详
**原文:**
_最大的难题：300ms延迟。2007年，苹果准备发布首款iPhone，需要解决一个问题，如何让用户浏览网页呢。早期的页面是为大屏幕设备设计的，那时也没有响应式，都是使用px作为字体的单位。因此用户浏览网页时会非常费劲，不是字体过`[去]`，就是页面只显示一部分。于是苹果工程师是想了一个办法，双击页面自动放大，再自击时页面回复原状。有了这设计，dblclick废掉了。_
**建议:**
最大的难题:  触屏交互300ms延迟.  在2007年苹果准备发布首款iPhone时, 他们的工程师需要解决如何让用户在手机上浏览那些为PC大屏幕设备而设计的网页, 那时候的网页并没有响应式设计, 并且都是使用px作为字体和元素尺寸的单位. 因此用户在使用iPhone浏览网页时体验非常糟糕, 不是字体过小, 就是页面只显示一部分. 于是苹果工程师想到了一个办法, 那就是如今大家习以为常的双击放大页面, 再次双击恢复页面功能. 有了这个设计之后, PC端的dblclick事件被废除掉了.

**Comment by michael829** [comment]
**位置:** 第3段
**问题:** 文字缺失及语义不详
**原文:**
_页面难免有大量链接，如果我们点击到某链接，如何区分用户是想打开新页面，还是放大页面呢？因此屏幕太小，难免有误操作。因此苹果工程师就让所有点击事件延迟一下，以判断用户是否再次点击屏幕。不过，这个只是为了开发者自己的方便，完全没有考虑到用户的感受。并且随着响`[应]`式设计的流行，我们也能完全在设计上避免上述情况。因此旧有的300ms延迟便成为众的之矢了。第一个起来针对它的库就是fastclick。_
**建议:**
网页中难免有大量链接, 如果我们在移动设备中访问网页时点击到某个链接, 如何区分用户是想打开该链接还是放大页面呢?  而且移动设备屏幕较小, 难道出现误操作. 因此苹果工程师就想到让所有的点击事件延迟一下, 以判断用户是否再次点击屏幕来判断用户的操作. 不过, 这个处理方式只是为了方便开发者, 完全没有考虑到用户的感受. 并且随着响应式设置的流行, 我们完全可以在设计之初就避免上述误点击的问题. 因为, 旧有的点击延迟便 成为众矢之的, 第一个针对此问题的库就是faskclick.

**位置:** 第4段
**问题:** 语义不详
**原文:**
_此外，智能手机上的交互基本上是通过手指1 进行的，要用一个手指或多个手指的动作来表述自己的意见......_
**建议:**
此外, 移动设备的交互基本上是通过手指1 进行的, 要使用一根手指或多根手指的动作向设备传达用户的意图...

位置: 第四段配图
问题: 文字错误
原图:
![-1475082569755](https://cloud.githubusercontent.com/assets/9690703/19262570/502a2726-8fca-11e6-9dbc-dbad7b1bb51c.png)
建议:
Rotation旋转事件
Pinch缩放事件
Swipe划动事件

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19301409/f426ccea-9091-11e6-96b2-550b907acd6d.png)

**Comment by michael829** [comment]
**位置:** 第5段
**问题:** 语义不详
**原文:**
_avalon的事件系统基本沿着它的设计改进过来，由于tap事件需要大费章幅模拟PC上的点击效果，因此独立出来_
**建议:**
avalon的事件系统基本上是以IOS手势事件为蓝本改进而来. 其中由于tap事件需要大费周章的模拟PC上的点击效果, 因为独立出来

**位置:** 第6段
**问题:** 语义不详
**原文:**
_本章介绍到的源代码在以下链接找到：_
**建议:**
本章介绍到的源代码都可以在以下链接找到：

**Comment by RubyLouvre** [comment]
你应该另开新ISSUE
