### ISSUE TITLE
第二章获取当前月天数 和前面获取 最后一天重复 可以合并成一个方法吧

### ISSUE THREAD

**Issue by mrswangs** [RubyLouvre/jsbook#129]
![ss](https://cloud.githubusercontent.com/assets/16077431/19263443/f67da5f4-8fce-11e6-8d5e-c5b60386a7ef.jpg)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19262497/e0dda96a-8fc9-11e6-9c0a-1ab2da763c49.png)

**Comment by RubyLouvre** [comment]
说了这么久都不知说哪里
