### ISSUE TITLE
哪3类

### ISSUE THREAD

**Issue by mrswangs** [RubyLouvre/jsbook#132]
我发现脚本语言都对字符串特别关注，有关它的方法特别多。我把这些方法分为三大类。

**Comment by RubyLouvre** [comment]
第几章？

**Comment by mrswangs** [comment]
第二章

**Comment by RubyLouvre** [comment]
不是叫你标题注明吗

**Comment by RubyLouvre** [comment]
已经改好，你刷新一下

![image](https://cloud.githubusercontent.com/assets/190846/19264381/24336a84-8fd3-11e6-922e-0e54f50b8dc6.png)
