### ISSUE TITLE
第九章第1节错误

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#133]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山
[checked=xxx]选中第四个元素
应改为[checked=xxx]选中第五个元素
![image](https://cloud.githubusercontent.com/assets/8122972/19266980/c0c42874-8fde-11e6-8282-1ea9a0601070.png)

**Comment by RubyLouvre** [comment]
好了，谢谢
