### ISSUE TITLE
第九章第1节 “外包“二字

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#134]
刘可 qq号75002425 avalon2群 深圳-萝卜皮 qq名 四分之山

此外，HTML5对属性进行了更多的分类，从外包到不同的对象
“外包”  什么意思，是否需要修改

![image](https://cloud.githubusercontent.com/assets/8122972/19267179/ea78f0f4-8fdf-11e6-86f0-b1382582256e.png)

**Comment by RubyLouvre** [comment]
HTML5对属性进行了更多的分类，打包到不同的对象中去
