### ISSUE TITLE
第九章第2节 阅读体验问题

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#135]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

![image](https://cloud.githubusercontent.com/assets/8122972/19267236/449a8278-8fe0-11e6-939d-d21caa9ccf5a.png)

"否决此方案"处，虽然9.2章节名称已经说明本节意图，但是读到此句依然感觉很突然

最好能在第64行结尾做些修改，建议改为：
我们需要做些实验找出其规律，从这些规律中，我们可以找到区分固有属性与自定义属性的方案。
![image](https://cloud.githubusercontent.com/assets/8122972/19267278/7c4480ac-8fe0-11e6-8d59-3690f3dccbbf.png)

**Comment by RubyLouvre** [comment]
666！
