### ISSUE TITLE
第九章第2节错别字

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#136]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

即使如此，我们也可以轻松绕过这个陷井
应改为陷阱
![image](https://cloud.githubusercontent.com/assets/8122972/19267349/d379d566-8fe0-11e6-9e02-a7c219debc0f.png)

**Comment by RubyLouvre** [comment]
好了
