### ISSUE TITLE
第九章第4节 书写错误

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#138]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

原文：因为我们是通过el.onclick绑定事件，而不是el.onclick。
改为：因为我们是通过el.onclick绑定事件，而不是el.onClick。
![image](https://cloud.githubusercontent.com/assets/8122972/19267462/6b3105dc-8fe1-11e6-9e63-df5495410e52.png)

**Comment by RubyLouvre** [comment]
https://www.baidu.com/s?ie=UTF-8&wd=el.onClick 都是使用小写的。 W3C规范的规定。所有标签属性都是小写化。
