### ISSUE TITLE
第九章第4节 书写错误

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#139]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

原文：因此style在IE下是个对象
改为：因为style在IE下是个对象

![image](https://cloud.githubusercontent.com/assets/8122972/19267521/b97f465e-8fe1-11e6-9101-828b214912f8.png)

**Comment by RubyLouvre** [comment]
好了
