### ISSUE TITLE
第九章 图小问题

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#141]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

jQuery的属性系统概览图，   钩子在所有特殊情况下都命中的结构图
这两个图太小看不清
![image](https://cloud.githubusercontent.com/assets/8122972/19267611/548cba78-8fe2-11e6-9da9-285cb6bd407e.png)
![image](https://cloud.githubusercontent.com/assets/8122972/19267622/5d6e3586-8fe2-11e6-9d65-403eeda8c24d.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19269474/5c8e04e2-8fed-11e6-9347-019acc434edb.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19269589/fee17670-8fed-11e6-9978-ffcfdf00adea.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19270698/df8ae5ee-8ff3-11e6-91db-ae201a5c1bde.png)
