### ISSUE TITLE
第九章第8节 代码错误

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#142]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

charoff缺少单引号

![image](https://cloud.githubusercontent.com/assets/8122972/19267653/84b85748-8fe2-11e6-8598-478d10385bcf.png)

**Comment by RubyLouvre** [comment]
这个本来就不需要引号，其他是因为用了关键字与横杠
