### ISSUE TITLE
第三章  文章第一句多了一个字

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#146]
原文：章节第一句：本模块是完全是服务节点操作模块，是处理兼容性的前线阵地。
建议：本模块完全是服务节点操作模块，是处理兼容性的前线阵地。
![image](https://cloud.githubusercontent.com/assets/22763487/19275826/671a54e6-9007-11e6-8756-8251ddfdf732.png)

**Comment by RubyLouvre** [comment]
好了
