### ISSUE TITLE
第三章  文章第二段语意不详

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#147]
原文：时至今日，浏览器嗅探现在已经不推荐了，但在某些场合我们还是需要的，比如一些统计脚本。
建议：句末“比如一些统计脚本”感觉不太通顺。
![image](https://cloud.githubusercontent.com/assets/22763487/19275981/bf576b08-9007-11e6-80b5-2f25ed195d0a.png)

**Comment by RubyLouvre** [comment]
时至今日，浏览器嗅探现在已经不推荐了，但在某些场合我们还是需要的，比如一些数据统计代码，著名的有站长统计、百度统计、腾讯统计、Google Analytics。
