### ISSUE TITLE
第三章  图小，有些看不清，全屏放大了也是

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#148]
![image](https://cloud.githubusercontent.com/assets/22763487/19276112/fb2c97fc-9007-11e6-8b53-a21d829f68d6.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19336053/c58cd8a8-913a-11e6-8f2d-28b5823649df.png)
