### ISSUE TITLE
第十章第4节 语句不通顺

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#154]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

改成什么作者可以再斟酌下

![image](https://cloud.githubusercontent.com/assets/8122972/19295887/280aacde-906a-11e6-8fd7-6f8d863548db.png)

**Comment by RubyLouvre** [comment]
不要这样，我都无法复制

**Comment by RubyLouvre** [comment]
改了
