### ISSUE TITLE
第十章第7节 图片未显示

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#157]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

![image](https://cloud.githubusercontent.com/assets/8122972/19296730/8bdffc90-9070-11e6-9be6-1418894e0bf2.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19296870/1bc4b4a8-9072-11e6-9986-459c41c09d1d.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19299476/13d0b20a-9087-11e6-85d5-6ca8a6c4d3b9.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19300129/1249f190-908b-11e6-9a32-8ece3366d6b2.png)
