### ISSUE TITLE
第十章第8节 图片未显示及文字修改

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#158]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

1.原文：avalon的事件系统只要由avalon.bind, avalon.ubind两个主要方法组成
   改为：avalon的事件系统主要由avalon.bind, avalon.ubind两个方法组成
2.图片未显示
3.原文：它与市场上的addEvent方法一样
   “市场上”三个字可以考虑换成其他

![image](https://cloud.githubusercontent.com/assets/8122972/19297817/e50a4172-907a-11e6-8cab-98c2b4d09848.png)

**Comment by RubyLouvre** [comment]
已经好了
