### ISSUE TITLE
第十章 第8节 不好理解

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#161]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

原文：而事件对象的修复，一般是将srcElement改成target，修正阻止事件冒泡与默认笨为这两个API。像opera与chrome，其实IE那一套方法还是支持的。

整段不好理解

![image](https://cloud.githubusercontent.com/assets/8122972/19298339/4ee6f7f8-907f-11e6-87c2-72f323c7955a.png)

**Comment by RubyLouvre** [comment]
至于怎样标准化事件对象， 所有框架的想法都趋于一致，都是将srcElement改成target，修正**停止事件传播**与**阻止默认行为**这两个API，加上timeStamp与originalEvent属性。像opera与chrome，它们是同时支持两套API。
