### ISSUE TITLE
第二章：图片问题

### ISSUE THREAD

**Issue by mrswangs** [RubyLouvre/jsbook#164]
![1](https://cloud.githubusercontent.com/assets/16077431/19298757/b310e010-9082-11e6-8a83-8191f332dd2b.png)

**Comment by RubyLouvre** [comment]
什么问题

**Comment by mrswangs** [comment]
右边缺了啊

**Comment by RubyLouvre** [comment]
不用管了，到时编辑能拿到图片

**Comment by RubyLouvre** [comment]
没有吧，
