### ISSUE TITLE
第二章：最后部分问题

### ISSUE THREAD

**Issue by mrswangs** [RubyLouvre/jsbook#165]
![2](https://cloud.githubusercontent.com/assets/16077431/19299116/057f8426-9085-11e6-9915-688d424c39b7.png)
![3](https://cloud.githubusercontent.com/assets/16077431/19299118/073f9ac6-9085-11e6-85a6-dd04653c6cc7.jpg)

这事件其实实现了javascript生态圈的弱点。
--弱点用暴露或者展现吧

**Comment by RubyLouvre** [comment]
这个是有题注的，在文章中

**Comment by RubyLouvre** [comment]
好了
