### ISSUE TITLE
第十一章第1节 语句重复

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#169]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

原文：虽然这些触摸事件没有在DOM规范中定义，但它们却是以兼容DOM的方式实现的。因此，每个触摸事件没有在DOM规范中定义，但它们却是以兼容DOM的方式实现的。
改为：虽然这些触摸事件没有在DOM规范中定义，但它们却是以兼容DOM的方式实现的。

![image](https://cloud.githubusercontent.com/assets/8122972/19304952/4abe2c88-90a1-11e6-8eec-a7c3f5c7d92b.png)

**Comment by RubyLouvre** [comment]
好了
