### ISSUE TITLE
第四章 第二节 def.js 图片太小了

### ISSUE THREAD

**Issue by zhangjinsong** [RubyLouvre/jsbook#173]
![book5](https://cloud.githubusercontent.com/assets/12949599/19316154/f0c11b28-90d2-11e6-8f9f-375cde498b88.png)

**Comment by RubyLouvre** [comment]
![image](https://cloud.githubusercontent.com/assets/190846/19335642/736f0aee-9137-11e6-9470-ffc7b99c0472.png)
