### ISSUE TITLE
第三章 文章第二段语意不详

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#175]
曹学进 qq号1282911984 avalon2群 云南

原文：时至今日，浏览器嗅探现在已经不推荐了，但在某些场合我们还是需要的，比如一些统计脚本。
建议：句末“比如一些统计脚本”感觉不太通顺。
![image](https://cloud.githubusercontent.com/assets/22763487/19332825/695b1dc8-9122-11e6-8f12-1423d6ade0d7.png)

**Comment by RubyLouvre** [comment]
好了
