### ISSUE TITLE
第十一章 第9节 文字修改

### ISSUE THREAD

**Issue by liuke8080** [RubyLouvre/jsbook#186]
刘可  qq号75002425   avalon2群 深圳-萝卜皮     qq名 四分之山

原文：不过本人认识微软提供的原生事件比touch系事件好用多
改为：不过本人认为微软提供的原生事件比touch系事件好用多

![image](https://cloud.githubusercontent.com/assets/8122972/19340334/fb7df4e0-915a-11e6-8219-c73d21666a4a.png)

**Comment by RubyLouvre** [comment]
好了
