### ISSUE TITLE
8.2 样式名的修正 文字错误

### ISSUE THREAD

**Issue by Jacky-Huang-1018** [RubyLouvre/jsbook#201]
原文：不是所有样式名都是直接用正则简单处理一下就行，这里存在三个**陷井**，float对应的JavaScript属性存在兼容性问题，CSS3大爆炸时带来的私有前缀，IE的私有前缀不合流问题。

修改：不是所有样式名都是直接用正则简单处理一下就行，这里存在三个**陷阱**，float对应的JavaScript属性存在兼容性问题，CSS3大爆炸时带来的私有前缀，IE的私有前缀不合流问题。

**Comment by RubyLouvre** [comment]
好了
