### ISSUE TITLE
第十五章 前端模板 2

### ISSUE THREAD

**Issue by Zjingwen** [RubyLouvre/jsbook#202]
原文：这就是官方推我们使用`$apply`驱动程序运行，而不直接用`$digest`的缘故。

建议：这就是官方推荐我们使用`$apply`驱动程序运行，而不直接用`$digest`的缘故。

---

原文：两个相同组件产生类似的DOM树结构，不同的组件产生不同的DOM结构树。

建议：两个相同组件产生类似的DOM树结构，不同的组件产生不同的DOM树结构。

---

原文：如下图，老集合中包含节点：A、B、C、D，更新后的新集合中包含节点：B、A、D、C，此时新老集合进行 diff 差异化对比，发现 B != A，则创建并插入 B 至新集合，删除老集合 A；以此类推，创建并插入 A、D 和 C，删除 B、C 和 D。

建议：全文有两段，一摸一样的话，建议删除搜索出来的第二段。

---

原文：以上图为例，可以更为清晰直观的描述 diff 的差异对比过程：

建议：貌似我没找到上图

---

原文：由于MVVM的便捷性，让前端更容易堆砌庞大的应用，于是它们比以往遇频繁遇到这两个问题。

建议：由于MVVM的便捷性，让前端更容易堆砌庞大的应用，于是它们比以往更加频繁的遇到这两个问题。（遇频繁遇，这个词我不是很理解意思。）

---

**Comment by RubyLouvre** [comment]
好了
