### ISSUE TITLE
第六章  6.1 语句冗余过长导致语意不通

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#203]
原文：fixScript顾名思义，用于修复innerHTML生成的script节点不会发出请求与执行text属性的行为
建议：fixScript顾名思义，用于修复innerHTML生成的script节点，不会发出请求与执行text属性的行为
![image](https://cloud.githubusercontent.com/assets/22763487/19675087/f49a5908-9abe-11e6-8d94-a364a623a0c2.png)

**Comment by RubyLouvre** [comment]
好了
