### ISSUE TITLE
第六章  6.2  错别字

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#204]
原文：在微软的DHTML推销过程中，又早出了insertAdjacentXXX三组方法：
建议：在微软的DHTML推销过程中，又造出了insertAdjacentXXX三组方法：
![image](https://cloud.githubusercontent.com/assets/22763487/19675231/c26cd1da-9abf-11e6-9b90-e7ded01f1867.png)

**Comment by RubyLouvre** [comment]
好了
