### ISSUE TITLE
第六章  6.2 多了一个字

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#205]
原文：(insertAdjacentHTML与insertAdjacentText要求传入这字符串，insertAdjacentElement要求传入节点)。
建议：(insertAdjacentHTML与insertAdjacentText要求传入字符串，insertAdjacentElement要求传入节点)。
![image](https://cloud.githubusercontent.com/assets/22763487/19675348/6623e066-9ac0-11e6-9338-9cfca51b681b.png)

**Comment by RubyLouvre** [comment]
好了
