### ISSUE TITLE
第六章    6.5.2  错别字导致语意不通

### ISSUE THREAD

**Issue by caoxuejin-ai** [RubyLouvre/jsbook#208]
原文：但无法是Mutation Event还是MutationObserver，对浏览器的版本要求还是非常高的
建议：但无论是Mutation Event还是MutationObserver，对浏览器的版本要求还是非常高的
![image](https://cloud.githubusercontent.com/assets/22763487/19678278/a0b75b18-9acf-11e6-9d19-327606b3d3b5.png)

**Comment by RubyLouvre** [comment]
好了
