### ISSUE TITLE
第十三章 数据交互模块

### ISSUE THREAD

**Issue by Zjingwen** [RubyLouvre/jsbook#213]
原文：凭心而论，上面的方法已经很高效了，只判定了一次，然后缓存生成方式。但有没有更优雅的设计呢？！

建议：凭心而论，上面的方法已经很高效了，只判定了一次，然后缓存生成方式。但有没有更优雅的设计呢？~~`!`~~

---

原文：IE10终于把这些事件一口气实现了，如`表13.1`所示。

建议：IE10终于把这些事件一口气实现了，如`下表`所示。

---

原文：
2.分离异步与同步处理

```
var ajax = $.ajax({
    url: "script.php",
    type: "POST",
    data: {
        id: menuId
    },
    dataType: "html"
}).fail(function(jqXHR, textStatus) {
    alert("Request failed: " + textStatus);
});


//同步还在执行代码，这个函数有可能在AJAX结束前调用
dosomething()
//同步还在执行代码，这个函数有可能在AJAX结束前调用
dosomething()

//异步还在等在成功响应
aajax.done(function(msg) {
    $("#log").html(msg);
})
```

建议：

```
aajax.done(function(msg) {
    $("#log").html(msg);
})

//aajax修改为ajax
```

---

原文：ajax自2005出现公众面前，已经有十多年，算是一个很长寿的技术方案了。而它的取替点，则安排w3c一惯的手段，从社区成熟的方案标准化。fetch，大抵可以认为jQuery.ajax的官方版。

建议：ajax自`2005年`出现公众面前，已经有十多年，算是一个很长寿的技术方案了。而它的取替点，则`根据`w3c一惯的手段，从社区成熟的方案标准化。fetch，大抵可以认为jQuery.ajax的官方版。

---

**Comment by RubyLouvre** [comment]
好了
