### ISSUE TITLE
第70页，第4章 4.4 浏览器特征检测

### ISSUE THREAD

**Issue by michaeljayt** [RubyLouvre/jsbook#6]
checkOn 的默认属性，书中标识 Chrome 中 checkbox 的默认 value 为空字符串，但是在当前稳定版本 (34.0.1847.116) 中经测试，使用：
1、document.createElement()方法
2、页面标签<input type="checkbox" />
value的默认值皆为"on"。

**Comment by RubyLouvre** [comment]
第三版已修正
