### ISSUE TITLE
第8页代码解释

### ISSUE THREAD

**Issue by janryWang** [RubyLouvre/jsbook#62]
有一个obj.item这个item是一个特殊属性还是啥，用它来干嘛的，还有，就是void 0这是干嘛的呢，求解答

**Comment by RubyLouvre** [comment]
在古老浏览器中，undefined并不是window的子属性，也不是关键字，不先定义undefined就使用会报错;
在IE6－8中，undefined不是关键字，只是window的子属性，会被覆盖，比如window.undefine = 1;
alert(undefined)会弹出1;因此防止被覆写，我们需要将undefined的副本保存在库的闭包里面，这也有助于提高性能。
而生成undefined的副本，使用void 0就是最简洁的写法，本书将大量使用void 0代替undefined。
