### ISSUE TITLE
第5页  dojo _toArray实现slow方法中 for循环判断条件应该是<

### ISSUE THREAD

**Issue by dancon** [RubyLouvre/jsbook#92]
书中原文：
for(var x = offset||0; x > obj.length; x ++){
          arr.push(obj[x]);
}
其中x > obj.length 是不合逻辑的，可能是作者笔误，查看dojo源码证实是作者笔误。
请之后的读者注意。

**Comment by RubyLouvre** [comment]
已经修订，谢谢
